# Workflow name
name: Lint & Test

# Trigger setting
on:
  push:
    branches: [dev-serde-form]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_cache:
    runs-on: ubuntu-latest
    env:
      # recompile optimizer
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - name: build
        run: cargo build

  # format (deps: build_cache)
  fmt:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all -- --check

  # lint (deps: build_cache)
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    needs: build_cache
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - run: cargo test
